<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerE2e1QzM\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerE2e1QzM/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerE2e1QzM.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerE2e1QzM\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerE2e1QzM\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'E2e1QzM',
    'container.build_id' => '7051ef07',
    'container.build_time' => 1561591296,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerE2e1QzM');
