<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOoc86mS\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOoc86mS/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOoc86mS.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOoc86mS\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerOoc86mS\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Ooc86mS',
    'container.build_id' => 'bd198c22',
    'container.build_time' => 1561518710,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOoc86mS');
